---
-  hosts: webserver
   become: True
   tasks:
   - name: install java and tomcat
     yum:
       name: "{{ item }}"
       state: latest
     with_items:
       - java-1.8.0
       - tomcat
       - tomcat-webapps
       - tomcat-admin-webapps
   - name: start service tomcat
     service:
       name: tomcat
       state: started
   - name: delete tomcat-users.xml 
     file:
       path: /etc/tomcat/tomcat-users.xml
       state: absent
   - name: copy user.xml file from github to ansible 
     copy:
       src: tomcat-users.xml
       dest: /etc/tomcat/
   - name: start service tomcat
     service:
       name: tomcat
       state: restarted
   - name: copy Artifacts from nexus 
     get_url:
       url: http://54.188.51.117:8081/nexus/service/local/repositories/gol/content/Dev/Dev/{{ $Build_ID }}/Dev-{{ $Build_ID }}.war
       dest: /usr/share/tomcat/webapps
